/**
 * Build-time script: reads Markdown under content/posts and writes
 * src/generated/posts-data.ts for Cloudflare Workers (no runtime fs).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import matter from "gray-matter";
import { remark } from "remark";
import remarkGfm from "remark-gfm";
import remarkHtml from "remark-html";
import { type Category, isValidCategory } from "../src/lib/categories";
import { locales, type Locale } from "../src/lib/i18n";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const postsRoot = path.join(root, "content/posts");
const outFile = path.join(root, "src/generated/posts-data.ts");

type GeneratedPost = {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  category: Category;
  tags: string[];
  pinned?: number;
  content: string;
};

function parseCategory(data: matter.GrayMatterFile<string>["data"]): Category {
  const raw = data.category as string | undefined;
  return raw && isValidCategory(raw) ? raw : "tech";
}

function parsePinned(data: matter.GrayMatterFile<string>["data"]): number | undefined {
  const raw = data.pinned;
  if (raw === true) return 999;
  if (typeof raw === "number" && raw > 0) return raw;
  return undefined;
}

async function loadLocalePosts(locale: Locale): Promise<GeneratedPost[]> {
  const dir = path.join(postsRoot, locale);
  if (!fs.existsSync(dir)) return [];

  const slugs = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => f.replace(/\.md$/, ""));

  const posts: GeneratedPost[] = [];

  for (const slug of slugs) {
    const fullPath = path.join(dir, `${slug}.md`);
    const { data, content } = matter(fs.readFileSync(fullPath, "utf8"));
    const html = await remark()
      .use(remarkGfm)
      .use(remarkHtml, { sanitize: false })
      .process(content);

    const pinned =
      data.pinned === true
        ? 999
        : typeof data.pinned === "number" && data.pinned > 0
          ? data.pinned
          : undefined;

    posts.push({
      slug,
      title: data.title as string,
      date: data.date as string,
      excerpt: (data.excerpt as string) ?? "",
      category: parseCategory(data),
      tags: (data.tags as string[]) ?? [],
      ...(pinned !== undefined ? { pinned } : {}),
      content: html.toString(),
    });
  }

  return posts.sort((a, b) => (a.date < b.date ? 1 : -1));
}

async function main() {
  const byLocale: Record<Locale, GeneratedPost[]> = { en: [], zh: [] };

  for (const locale of locales) {
    byLocale[locale] = await loadLocalePosts(locale);
  }

  const total = byLocale.en.length + byLocale.zh.length;
  console.log(`Generated ${total} posts (en: ${byLocale.en.length}, zh: ${byLocale.zh.length})`);

  fs.mkdirSync(path.dirname(outFile), { recursive: true });

  const body = `// Auto-generated by scripts/generate-posts.ts — do not edit.
import type { Category } from "@/lib/categories";
import type { Locale } from "@/lib/i18n";

export type GeneratedPost = {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  category: Category;
  tags: string[];
  pinned?: number;
  content: string;
};

export const postsData: Record<Locale, GeneratedPost[]> = ${JSON.stringify(byLocale, null, 2)} as Record<Locale, GeneratedPost[]>;
`;

  fs.writeFileSync(outFile, body, "utf8");
  console.log(`Wrote ${outFile}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
